#-------------------------------------------------------------------------------
# 1.13+ entity mapping
#-------------------------------------------------------------------------------

#if MC_VERSION >= 11300

# Weak SSS
entity.10015 = cow pig sheep chicken zombie zombie_villager minecraft:player_cape minecraft:elytra_with_cape

# Strong white light
entity.10032 = tnt minecraft:end_crystal_beam

# Medium full emissives
entity.10033 = vex shulker_bullet firework_rocket

# Dim full emissives
entity.10034 = glow_item_frame

# Strong golden light
entity.10035 = blaze

# Partial emissives
entity.10036 = spectral_arrow bigglobe:torch_arrow

# Weak golden light
entity.10037 = evoker

# Lava
entity.10039 = fireball

# Fire
entity.10040 = magma_cube small_fireball minecraft:entity_flame

# Blue light
entity.10043 = allay ad_astra:star_crawler

# End portal frame / Glow squid
entity.10045 = eye_of_ender glow_squid

# Sculk
entity.10046 = warden

# Pink glow
entity.10047 = end_crystal dragon_fireball

# Sea Pickle
#entity.10048 =

# Experience
entity.10052 = experience_bottle experience_orb

# Enchanting table / End mobs
entity.10054 = enderman endermite ender_dragon minecraft:zombie_villager_converting

# Item
entity.10100 = item

# Boats
entity.10101 = boat chest_boat smallships:brigg smallships:cog smallships:drakkar smallships:galley

# Lightning bolt
entity.10102 = lightning_bolt

# Player
entity.10103 = player

# Drowned (Material 10036 and Light 10048)
entity.10104 = drowned phantom

# Area effect cloud (Pink glow in end)
entity.10105 = area_effect_cloud

# Stained glass and slime
entity.10169 = slime

# Transparent
entity.10256 = painting


# Red
entity.10280 = coloredendcrystals:red_end_crystal coloredendcrystals:colored_end_crystal:color=red

# Orange
entity.10281 = coloredendcrystals:orange_end_crystal

# Yellow
entity.10282 = yellow_candle:lit=true:candles=2

# Brown
entity.10283 = brown_candle:lit=true:candles=2

# Green
entity.10284 = coloredendcrystals:colored_end_crystal:color=green

# Lime
entity.10285 = lime_candle:lit=true:candles=2 mythicupgrades:jade_crystal_cluster mythicupgrades:[BudSize]_jade_crystal_bud

# Blue
entity.10286 = blue_candle:lit=true:candles=2

# Light blue
entity.10287 = light_blue_candle:lit=true:candles=2

# Cyan
entity.10288 = cyan_candle:lit=true:candles=2 mythicupgrades:aquamarine_crystal_cluster mythicupgrades:[BudSize]_aquamarine_crystal_bud

# Purple
entity.10289 = purple_candle:lit=true:candles=2 mythicupgrades:ametrine_crystal_cluster mythicupgrades:[BudSize]_ametrine_crystal_bud

# Magenta
entity.10290 = magenta_candle:lit=true:candles=2

# Pink
entity.10291 = pink_candle:lit=true:candles=2

# Black
entity.10292 = black_candle:lit=true:candles=2

# White
entity.10293 = white_candle:lit=true:candles=2

# Gray
entity.10294 = gray_candle:lit=true:candles=2

# Light gray
entity.10295 = light_gray_candle:lit=true:candles=2


# Drowned (Material 10036 and Light 10048)
#entity.20000 = drowned phantom

# Area effect cloud (Pink glow in end)
#entity.20001 = area_effect_cloud

#-------------------------------------------------------------------------------
# 1.12 entity mapping
#-------------------------------------------------------------------------------

#else

#endif
